### ISSUE TITLE
Integer Id object

### ISSUE THREAD

**Issue by viceroypenguin** [martinothamar/WrapperValueObject#1]
If I have an `int ProductId`, then I don't want the math operator overloads to be provided. Recommendations for improvement:
* If the object ends w/ `Id`, then don't add the math operators by default
* Add a flag to the Attribute that allows override (I _do_ or _do not_ want math operators)

**Comment by viceroypenguin** [comment]
NB: If you want, I can do some work and give you a PR for this.

**Comment by martinothamar** [comment]
> Add a flag to the Attribute that allows override
This is what I've considered before and I'm sure there are more scenarios where this would be a good option

Special handling for `Id` could also work. Maybe a combination? So that if you want math operator for ID types (though I don't know if this ever happens) its atleast possible.

Yeah feel free to create a PR 👍

**Comment by viceroypenguin** [comment]
Turns out it doesn't matter. The implicit conversion operator back to `int` means without the operator, the compiler can still create a valid `+` operation for the struct. Probably need to add another attribute to optionally disable the implicit operator back to the primitive.

**Comment by martinothamar** [comment]
Good point! Merged the PR, were som build issues but resolved that and pushed the alpha08 release just now. Thanks 😃

**Comment by viceroypenguin** [comment]
Thanks for the quick release!
